services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
      - "8080:8080"
      - "50051:50051"
    volumes:
      - .:/app
    env_file:
      - env
    restart: always
    depends_on:
      - rabbitmq
      - db-mysql

  db-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./sql/migrations:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest